### ISSUE TITLE
Dup Bug

### ISSUE THREAD

**Issue by KRUNCHSHooT** [iLVOEWOCK/AutoInventory#1]
several plugins have canceled BlockBreakEvent and this plugin is still running so blocks that enter the inventory can be continuously obtained. I suggest making it have a high priority so that it can be run last and given a condition where if the event is canceled it will not run the code.

**Comment by iLVOEWOCK** [comment]
Is there a way i can reproduce this bug?

**Comment by bobbyshmurdaa99** [comment]
i will work this out tomorrow, i think i have an understanding.

**Comment by KRUNCHSHooT** [comment]
Try Make a plugin that cancelling BlockBreakEvent like EconomyLand or Some plugin with an Area lock system. Or you can try Economy Land if you want

**Comment by iLVOEWOCK** [comment]
I see, so for example plugins like RegionProtect right? im gonna do my testing with this plugin and a few others.

**Comment by iLVOEWOCK** [comment]
i believe i resolved the issue. i used this plugin is my test.

https://github.com/kaidomc-pm-pl/RegionProtect/tree/master

if you run into any issues please open a new issue,
